#!/usr/bin/env python3
"""K1 — emit FROZEN_STATE.md. Phase 0 of an audit, mechanised.

    python3 scripts/audit/freeze_state.py > audit/FROZEN_STATE.md

An audit that cannot say what it audited cannot be reproduced, and the
2026-09-22 audit spent real effort assembling this by hand. Everything here is
read from the machine, so it cannot drift from what was actually examined.

WHAT THIS RECORDS THAT A NAIVE VERSION WOULD MISS, each because it mattered:

* **Ambient environment that is NOT the product default.** The audit ran with
  `LLM_ROUTER_CLAUDE_SUBSCRIPTION=true` and several ensemble flags set in the
  operator's shell. Any behaviour observed under those is not what a new
  installation does, and an audit that does not say so reports the operator's
  configuration as the product.

* **Absent credentials.** "The OpenAI path was never exercised" is a different
  statement from "the OpenAI path works", and only the frozen state can tell
  them apart afterwards.

* **A conflict-of-interest declaration.** When the same model writes the code,
  fixes it, and judges the fix, correlated failure is the default and not the
  exception. Recording it does not remove it; leaving it out hides it.

Secrets are NEVER printed — only whether a variable is set. The point is to
record the shape of the environment, not its contents.

NEITHER ARE PERSONAL PATHS. This file is committed to a PUBLIC repository, and
the first draft printed `sys.executable` — which on a developer machine is
`/Users/<name>/...`. Absolute paths under a home directory are redacted to
`~/...`, and a bare interpreter path is reduced to whether it is a venv. An
audit artifact should record the SHAPE of a machine, never whose machine it
was.
"""

from __future__ import annotations

import os
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

#: Env vars whose PRESENCE changes behaviour. Values are never printed — for
#: the credentials this is a secrecy rule, and for the flags it keeps the
#: report about shape rather than settings.
BEHAVIOUR_FLAGS = (
    "LLM_ROUTER_HOME", "LLM_ROUTER_ENFORCE", "LLM_ROUTER_PROFILE",
    "LLM_ROUTER_CLAUDE_SUBSCRIPTION", "LLM_ROUTER_ZERO_CLAUDE",
    "LLM_ROUTER_GROUND_TRUTH", "LLM_ROUTER_AGENT_COMMANDS",
    "LLM_ROUTER_AGENT_WRITES", "LLM_ROUTER_DB_PATH",
    "LLM_ROUTER_SIDECAR_PREFETCH", "LLM_ROUTER_BASH_INTERCEPT",
    "LLM_ROUTER_GATEWAY_TOKEN", "LLM_ROUTER_ALERT_WEBHOOK",
)

CREDENTIALS = (
    "OPENAI_API_KEY", "ANTHROPIC_API_KEY", "GEMINI_API_KEY",
    "GOOGLE_API_KEY", "PERPLEXITY_API_KEY", "GROQ_API_KEY",
    "DEEPSEEK_API_KEY", "OPENROUTER_API_KEY",
)


def _redact(text: str) -> str:
    """Replace the operator's home directory with `~`.

    Applied to everything that could carry a filesystem path. The repo is
    public; a frozen-state file naming a person's home directory identifies
    them, and it says nothing an auditor needs.
    """
    home = str(Path.home())
    out = text.replace(home, "~")
    # A different user's home under the same root, e.g. /Users/<other>/…
    parent = str(Path.home().parent)
    if parent not in ("/", ""):
        import re
        out = re.sub(rf"{re.escape(parent)}/[^/\s]+", "~<other-user>", out)
    return out


def _sh(*args: str) -> str:
    try:
        r = subprocess.run(args, cwd=REPO, capture_output=True, text=True, timeout=30)
        return (r.stdout or r.stderr).strip()
    except Exception as exc:  # noqa: BLE001
        return f"<unavailable: {type(exc).__name__}>"


def _count(pattern: str) -> int:
    return sum(1 for _ in REPO.glob(pattern))


def main() -> int:
    out: list[str] = []
    w = out.append

    w("# Frozen state")
    w("")
    w("Generated by `scripts/audit/freeze_state.py` (K1). Do not hand-edit —")
    w("regenerate it, or the record stops matching what was audited.")
    w("")
    w(f"- Generated: {datetime.now(timezone.utc).isoformat()}")
    w(f"- HEAD: `{_sh('git', 'rev-parse', 'HEAD')}`")
    w(f"- Branch: `{_sh('git', 'rev-parse', '--abbrev-ref', 'HEAD')}`")
    dirty = _sh("git", "status", "--porcelain")
    w(f"- Working tree: {'DIRTY — the audit did not examine a committed state' if dirty else 'clean'}")
    if dirty:
        for line in dirty.splitlines()[:20]:
            w(f"    {_redact(line)}")
    in_venv = sys.prefix != getattr(sys, "base_prefix", sys.prefix)
    w(f"- Python: {platform.python_version()} "
      f"({'project venv' if in_venv else 'system interpreter'})")
    w(f"- Platform: {platform.platform()}")
    w("")

    w("## Size")
    w("")
    src = len(list((REPO / "src").rglob("*.py")))
    tests = len(list((REPO / "tests").rglob("test_*.py")))
    w(f"- source files: {src}")
    w(f"- test files: {tests}")
    w("")

    w("## Ambient environment — NOT the product default")
    w("")
    w("Behaviour observed with these set is not what a fresh install does.")
    w("")
    set_flags = [(k, os.environ.get(k)) for k in BEHAVIOUR_FLAGS if os.environ.get(k)]
    if set_flags:
        w("| variable | set to |")
        w("|---|---|")
        for k, v in set_flags:
            # Tokens and webhooks are SET/UNSET only; the rest carry their value
            # because the value is the behaviour.
            if "TOKEN" in k or "WEBHOOK" in k:
                shown = "(set)"
            else:
                # Redacted: LLM_ROUTER_HOME and LLM_ROUTER_DB_PATH are paths
                # under the operator's home directory.
                shown = f"`{_redact(v)}`"
            w(f"| `{k}` | {shown} |")
    else:
        w("None set — this run used product defaults.")
    w("")

    w("## Credentials")
    w("")
    w("Presence only. An absent key means that provider path was NEVER")
    w("EXERCISED, which is a different claim from it working.")
    w("")
    w("| provider key | present |")
    w("|---|---|")
    for k in CREDENTIALS:
        w(f"| `{k}` | {'yes' if os.environ.get(k) else 'NO'} |")
    w("")

    w("## Local backends")
    w("")
    ollama = _sh("bash", "-lc", "command -v ollama >/dev/null && ollama list 2>/dev/null | tail -n +2 | wc -l || echo unavailable")
    w(f"- ollama models available: {_redact(ollama)}")
    w(f"- git: {_redact(_sh('git', '--version'))}")
    w("")

    w("## Conflict of interest")
    w("")
    w("The same model wrote much of this code, produced the remediation, and")
    w("wrote the tests that check it. Correlated failure is the DEFAULT in that")
    w("arrangement, not an edge case: a blind spot in the author is a blind spot")
    w("in the reviewer and in the test. Recording this does not remove it.")
    w("")
    w("What partially mitigates it, and what does not:")
    w("")
    w("- Red-checks with the NARROWEST mutation (see CLAUDE.md, K7) catch a test")
    w("  that never exercised its claim. They do not catch a claim nobody made.")
    w("- Premise assertions catch a fix aimed at a non-defect. Three did, in one")
    w("  session.")
    w("- Independent specialists on a different model reduce correlation. They do")
    w("  not eliminate it, and at least one of their findings was wrong in a way")
    w("  that took re-derivation to see.")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
