"""RED8-10 — every environment variable the code reads must be declared.

195 variables are read across 313 sites and nothing declared them. The audit
counted 186; by the time it was measured here it was 195, and nobody had noticed
the drift. That is the defect: a config surface nobody has enumerated cannot be
documented or validated, and grows without anyone deciding it should.

THE CIRCULARITY THIS FILE EXISTS TO AVOID
-----------------------------------------
The registry could have been generated by walking the AST at import time. Then
this test — which also walks the AST — would compare a scan against itself and
pass unconditionally. That is not hypothetical; this audit has already found the
same shape twice:

  * ``tool_surface.unregistered()`` validated tier constants against ``_TIERS``,
    which IS the tier constants. A bogus canonical tool name passed the lint and
    106 tests, and blind spot Q3(c) was recorded as CLOSED on that basis.
  * ``scripts/lint_tool_surface.py`` checks emitters against emitters and still
    reports "clean" under that same mutation.

So ``ENV_REGISTRY`` is a hand-committed DECLARATION and the scan below is
INDEPENDENT ground truth. They are different artifacts, and the test compares
them. That is the only arrangement in which the test can fail.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

from llm_router import env_registry

_SRC = Path(env_registry.__file__).resolve().parent


def _env_reads_in_source() -> dict[str, set[str]]:
    """Every env var name read under src/llm_router, by AST. Ground truth.

    Deliberately re-implemented here rather than imported from the registry
    module: sharing the scanner would reintroduce the circularity, since a bug in
    the scanner would then hide itself on both sides of the comparison.
    """
    found: dict[str, set[str]] = {}
    for path in sorted(_SRC.rglob("*.py")):
        if path.name == "env_registry.py":
            continue
        # Deliberately NOT wrapped in try/except SyntaxError: continue.
        #
        # Skipping a file that will not parse makes the scan silently cover less
        # of the codebase than it claims -- the exact under-reporting this file's
        # header warns about, and worse here than elsewhere because the scan is
        # the INDEPENDENT ground truth the registry is checked against. A source
        # file under src/llm_router that cannot be parsed is a real problem and
        # should fail loudly with a traceback naming it, not vanish from the
        # denominator.
        #
        # It was also a G4 violation: `except SyntaxError: continue` is a no-op
        # handler, and this one pushed the ratchet to 35 > 34.
        tree = ast.parse(path.read_text())
        rel = str(path.relative_to(_SRC))
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                fn = node.func
                if getattr(fn, "attr", None) in ("get", "getenv") and node.args:
                    src = ast.unparse(fn)
                    if "environ" in src or "getenv" in src:
                        arg = node.args[0]
                        if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                            found.setdefault(arg.value, set()).add(rel)
            if isinstance(node, ast.Subscript):
                src = ast.unparse(node.value)
                if "environ" in src and isinstance(node.slice, ast.Constant):
                    if isinstance(node.slice.value, str):
                        found.setdefault(node.slice.value, set()).add(rel)
    return found


def test_the_scan_finds_something():
    """Guards the guard. If the scanner silently returns nothing, every
    assertion below passes vacuously and this file becomes decorative — the
    exact failure mode that let a broken probe report '0/6 reproductions'
    earlier in this audit."""
    reads = _env_reads_in_source()
    assert len(reads) > 100, f"scanner found only {len(reads)} env reads"
    assert "LLM_ROUTER_ENFORCE" in reads


def test_every_env_var_read_is_registered():
    """The criterion: every env var read anywhere appears in the registry."""
    reads = _env_reads_in_source()
    undeclared = sorted(set(reads) - env_registry.registered_names())
    assert not undeclared, (
        "environment variables read but not declared in llm_router.env_registry:\n"
        + "\n".join(f"  {n}  (read in {sorted(reads[n])[0]})" for n in undeclared)
    )


#: Read through a VARIABLE rather than a string literal, so the AST scan below
#: structurally cannot see them. Declared by hand in the registry and exempted
#: here. Keep this list SHORT: every entry is a hole in the scan, and a long list
#: means the scan has stopped describing the codebase.
_INDIRECT_READS = frozenset({
    "LLM_ROUTER_ALLOW_PUBLIC_BIND",
    "LLM_ROUTER_SSE_ALLOW_PUBLIC",
    # GH#68/#70/#71: the only LITERAL reads of these two were in
    # commands/verify_enterprise.py, removed along with the rest of the
    # dead enterprise surface. Both still have live readers — identity.py
    # reads them through the LLM_ROUTER_TOKEN_ENV / (audit is read through
    # misroute_audit.py's own _AUDIT_DISABLED_ENV) constant — but only
    # through a variable, so the literal-arg scan can't see them anymore.
    "LLM_ROUTER_TOKEN",
    "LLM_ROUTER_AUDIT_DISABLED",
})


def test_the_scanner_cannot_see_indirect_reads():
    """Pins the KNOWN LIMIT rather than leaving it implicit.

    net_bind.py does `for env in (A, B): os.environ.get(env)`. A scan that
    matches only literal arguments misses that, and so would any similar tool.
    Asserting the limit means a future maintainer meets it as a documented fact
    instead of as a silent gap.
    """
    reads = _env_reads_in_source()
    for name in _INDIRECT_READS:
        assert name not in reads, (
            f"{name} is now a LITERAL read — remove it from _INDIRECT_READS so "
            "the scan covers it directly"
        )
        assert name in env_registry.registered_names(), (
            f"{name} is read indirectly and must be declared by hand"
        )


def _owner_is_shipped(entry) -> bool:
    """True if the module that reads this variable exists in this tree.

    The registry records its owning file — ``("llm_router", "enterprise/audit.py",
    1)``. A variable read only by a module that was not shipped is not a
    phantom: nothing reads it because nothing that reads it is here.

    This matters for redistributions built from a subset of the source, where
    ``enterprise/``, ``admin_api`` and friends are excluded by design. Without
    this, six perfectly correct entries were reported as fiction and the only
    "fix" the message suggests — delete them — would have removed the
    documentation for variables that work fine in the full distribution.
    """
    try:
        relative = entry[1]
    except (IndexError, TypeError):
        return True  # malformed entry: let the other tests judge it
    if not isinstance(relative, str) or not relative:
        return True
    return (Path(env_registry.__file__).parent / relative).exists()


def test_the_registry_has_no_phantom_entries():
    """A registry that outlives its variables rots into fiction. An entry for a
    var nothing reads is as misleading as a missing one."""
    reads = _env_reads_in_source()
    candidates = (
        env_registry.registered_names() - set(reads) - _INDIRECT_READS
    )
    phantom = sorted(
        name
        for name in candidates
        if _owner_is_shipped(env_registry.ENV_REGISTRY[name])
    )
    assert not phantom, (
        "declared but never read (delete these, or the registry stops describing "
        "reality):\n" + "\n".join(f"  {n}" for n in phantom)
    )


def test_every_entry_has_a_known_category():
    bad = {
        name: entry[0]
        for name, entry in env_registry.ENV_REGISTRY.items()
        if entry[0] not in env_registry.CATEGORIES
    }
    assert not bad, f"unknown categories: {bad}"


def test_credentials_are_categorised_as_such():
    """Mis-filing a credential is how it ends up in a debug dump. Anything whose
    name says key/token/secret must be flagged, so a future 'print the config'
    feature has something to check against."""
    # A name that POINTS AT a secret is not itself one: LLM_ROUTER_BROKER_SECRET_FILE
    # holds a path and LLM_ROUTER_SECRETS_BACKEND names a mechanism. Filing those as
    # credentials would train the reader to ignore the category.
    _locators = ("_FILE", "_BACKEND", "_PATH", "_DIR", "_ENABLED", "_MODE")
    suspicious = {
        name for name in env_registry.ENV_REGISTRY
        if any(t in name.upper() for t in ("API_KEY", "_TOKEN", "SECRET", "ADMIN_KEY"))
        and not name.upper().endswith(_locators)
    }
    mis_filed = {
        n for n in suspicious
        if env_registry.category_of(n) != "provider_credential"
    }
    assert not mis_filed, f"credential-shaped names not filed as credentials: {sorted(mis_filed)}"


@pytest.mark.parametrize("name", ["LLM_ROUTER_ENFORCE", "LLM_ROUTER_ALLOW_PUBLIC_BIND"])
def test_load_bearing_vars_are_present(name):
    """Spot-check two that gate real behaviour: the enforcement mode and the
    public-bind opt-in. If either silently vanished, the registry would still be
    'complete' by the scan test alone."""
    assert env_registry.category_of(name) == "llm_router"
