"""Regression: GH#45 — uninstall left the probe cache behind.

`~/.llm-router/agentic_models.json` is written by the background
model-capability probe install kicks off (`agentic_registry.CACHE_PATH`).
Nothing in `uninstall()` or the install manifest removed it, so a plain
`llm-router uninstall` left it on disk. Only `--purge` cleared it, and that
deletes the whole state directory.

The state directory deliberately survives a plain uninstall, because it holds
`usage.db` (cost history) and `.env` (API keys) — things a user would not want
silently destroyed. That reasoning does not extend to a DERIVED CACHE: it is
regenerated by the next probe, holds nothing the user authored, and is stale
the moment the model set changes. So the distinction these tests pin down is
not "state dir survives" vs "state dir is deleted" — it is user data vs
regenerable cache, within a surviving state dir.
"""
from __future__ import annotations

import json

import pytest

import llm_router.agentic_registry as ar
import llm_router.commands.uninstall as un


@pytest.fixture
def state_dir(tmp_path, monkeypatch):
    """A throwaway ~/.llm-router holding the cache plus real user data."""
    d = tmp_path / ".llm-router"
    d.mkdir()
    cache = d / "agentic_models.json"
    cache.write_text(json.dumps({"probed_at": 0, "models": {}}) + "\n")
    (d / "usage.db").write_bytes(b"SQLite format 3\x00")
    (d / ".env").write_text("OPENAI_API_KEY=sk-not-a-real-key\n")

    monkeypatch.setattr(ar, "CACHE_PATH", cache)
    # Keep the run hermetic: only the state-dir behaviour is under test.
    monkeypatch.setattr(un, "_run_uninstall_surfaces", lambda: [], raising=False)
    return d


def test_cache_is_removed_by_a_plain_uninstall(state_dir):
    actions = un._remove_derived_state()
    assert not (state_dir / "agentic_models.json").exists(), (
        "GH#45: the probe cache survived uninstall"
    )
    assert any("agentic_models.json" in a for a in actions), actions


def test_user_data_is_never_touched(state_dir):
    """The whole reason the state dir survives a plain uninstall."""
    un._remove_derived_state()
    assert (state_dir / "usage.db").exists(), "uninstall destroyed cost history"
    assert (state_dir / ".env").exists(), "uninstall destroyed the user's API keys"
    assert "sk-not-a-real-key" in (state_dir / ".env").read_text()


def test_state_directory_itself_survives(state_dir):
    un._remove_derived_state()
    assert state_dir.is_dir(), "plain uninstall must not delete ~/.llm-router/"


def test_is_idempotent_when_no_cache_exists(state_dir):
    un._remove_derived_state()
    actions = un._remove_derived_state()  # second run
    assert not any("agentic_models.json" in a for a in actions), (
        f"second run should report nothing: {actions}"
    )


def test_reports_rather_than_raising_when_removal_fails(state_dir, monkeypatch):
    """A cleanup failure must never abort uninstall — the GH#42 lesson."""
    import pathlib

    real_unlink = pathlib.Path.unlink

    def _boom(self, *a, **k):
        if self.name == "agentic_models.json":
            raise OSError("permission denied")
        return real_unlink(self, *a, **k)

    monkeypatch.setattr(pathlib.Path, "unlink", _boom)
    actions = un._remove_derived_state()  # must not raise
    assert any("WARN" in a for a in actions), actions
