#!/usr/bin/env python3
"""Generate and check the bug index (plan v16 BUGS-1, D-R8-1 = A).

Bug entries are files: docs/bugs/<file_name(id)>.md, each starting with a
front-matter block (`id:` and `status:`) followed by the entry text.  Because
every PR adds its own file, concurrent PRs merge without a shared hunk.  The
index is therefore generated, never committed (a committed index would be the
shared hunk again).

    python scripts/bugs_index.py                 # print the index
    python scripts/bugs_index.py --write PATH    # save it
    python scripts/bugs_index.py --check         # integrity checks (CI)
    python scripts/bugs_index.py --check --index PATH   # also: PATH is not stale
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REQUIRED = (
    ("Symptom", ("Symptom",)),
    ("Cause", ("Cause",)),
    ("Fix", ("Fix",)),
    # GE6-2 names its check "Check": a test that cannot exist is still a named check.
    ("Test", ("Test", "Check")),
)
REF_RE = re.compile(r"BUGS\.md,?[ \t]+(?:bug[ \t]+)?#?([^\s\"'`,;:]+)")
ID_LIKE = re.compile(r"^(\d+|[A-Z][A-Za-z0-9.]*-[A-Za-z0-9]+)$")


def file_name(entry_id: str) -> str:
    """Filesystem-safe name for an id: digits -> 0001, '.' and '/' -> '_'."""
    if entry_id.isdigit():
        return f"{int(entry_id):04d}.md"
    return entry_id.replace(".", "_").replace("/", "_") + ".md"


@dataclass
class Entry:
    id: str
    status: str
    title: str
    body: str
    path: Path


def parse_entry(path: Path) -> Entry:
    text = path.read_bytes().decode("utf-8")
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].rstrip("\r\n") != "---":
        raise ValueError(f"{path}: no front matter")
    meta: dict[str, str] = {}
    end = None
    for i, ln in enumerate(lines[1:], start=1):
        if ln.rstrip("\r\n") == "---":
            end = i
            break
        key, _, val = ln.rstrip("\r\n").partition(": ")
        meta[key.strip()] = val
    if end is None or "id" not in meta:
        raise ValueError(f"{path}: bad front matter (need id, closing ---)")
    body = "".join(lines[end + 1:])
    m = re.match(r"## (\S+?)\. (.*)", body)
    title = m.group(2).strip() if m else ""
    return Entry(meta["id"], meta.get("status", ""), title, body, path)


def _sort_key(e: Entry):
    return (0, int(e.id), "") if e.id.isdigit() else (1, 0, e.id)


def load(root: Path) -> list[Entry]:
    bugs = root / "docs" / "bugs"
    return [parse_entry(p) for p in sorted(bugs.glob("*.md"))]


def render(entries: list[Entry]) -> str:
    out = [
        "# Bug index (generated by scripts/bugs_index.py; do not edit, do not commit)",
        "",
        "| id | file | status | title |",
        "|---|---|---|---|",
    ]
    for e in sorted(entries, key=_sort_key):
        cell = lambda s: s.replace("|", "\\|")  # noqa: E731
        out.append(f"| {e.id} | {e.path.name} | {cell(e.status)} | {cell(e.title)} |")
    return "\n".join(out) + "\n"


def check(root: Path, index: Path | None) -> list[str]:
    problems: list[str] = []
    entries: list[Entry] = []
    for p in sorted((root / "docs" / "bugs").glob("*.md")):
        try:
            entries.append(parse_entry(p))
        except ValueError as exc:
            problems.append(str(exc))
    seen: dict[str, Path] = {}
    for e in entries:
        if e.id in seen:
            problems.append(f"duplicate id {e.id}: {seen[e.id].name} and {e.path.name}")
        seen.setdefault(e.id, e.path)
        if e.path.name != file_name(e.id):
            problems.append(f"{e.id}: file is {e.path.name}, expected {file_name(e.id)}")
        if not e.body.startswith(f"## {e.id}. "):
            problems.append(f"{e.id}: body must start with '## {e.id}. <title>'")
        for label, alts in REQUIRED:
            if not any(re.search(rf"\*\*{a}\b", e.body) for a in alts):
                problems.append(f"{e.id}: missing the {label} heading (**{alts[0]}.**)")
    ids = set(seen)
    for sub in ("src", "tests"):
        base = root / sub
        if not base.is_dir():
            continue
        for f in sorted(base.rglob("*")):
            if f.suffix not in (".py", ".md", ".txt") or not f.is_file() or "fixtures" in f.parts \
                    or f.name == "test_bugs_split.py":  # its fixtures name ids on purpose
                continue
            for m in REF_RE.finditer(f.read_text(errors="ignore")):
                tok = m.group(1).rstrip(".)]}")
                if ID_LIKE.match(tok) and tok not in ids:
                    problems.append(f"{f.relative_to(root)}: BUGS.md reference '{tok}' resolves to no entry")
    pointer = root / "docs" / "BUGS.md"
    if pointer.exists() and re.search(r"^\|", pointer.read_text(), re.M):
        problems.append("docs/BUGS.md carries a table; it must stay a pointer")
    if index is not None:
        if not index.exists() or index.read_text() != render(entries):
            problems.append(f"stale index: {index} differs from the entry files; regenerate with --write")
    return problems


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    ap.add_argument("--write", type=Path)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--index", type=Path, help="with --check: an index file that must match")
    a = ap.parse_args(argv)
    if a.check:
        problems = check(a.root, a.index)
        for p in problems:
            print(f"bugs-check: {p}")
        n = len(load(a.root)) if not problems else "?"
        print(f"bugs-check: {'FAIL' if problems else 'ok'} ({n} entries)")
        return 1 if problems else 0
    text = render(load(a.root))
    if a.write:
        a.write.write_text(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
