"""TURNFIRST-1: which population a ``turn_first`` row is measured on.

``steps.step_kind`` called every non-first, non-continuation call ``turn_first``, so a
sub-agent's SendMessage resume and a ``<task-notification>`` turn were counted as human
turns: in the live ledger (2026-10-08 17:50 to 10-09 21:05) all 113 classified turn_first
rows were Sonnet sub-agent calls and 108 of them (95.6%) were classed ``code``. And
``steps._human_text`` stripped only ``<system-reminder>`` blocks, non-greedily, so harness
tags read as typed text and a literal close tag quoted inside a reminder leaked the rest of
the reminder. Synthetic text only; no prompt from any real session.
"""
from __future__ import annotations

import json
import random
import re

import pytest

from llm_router.groundtruth_sources import HARNESS_TAGS
from llm_router.proxy import backends as pb
from llm_router.proxy import steps
from llm_router.proxy import tiers as pt
from llm_router.proxy.cache_cost import Stickiness
from tests.test_proxy_tiers import Upstream, _app, _post, _rows

TOOLS = [{"name": "Read", "description": "read", "input_schema": {"type": "object"}}]
LAUNCHER = {"name": "Agent", "description": "launch a sub-agent", "input_schema": {"type": "object"}}
NOTIFICATION = ("<task-notification>\n<task-id>b1</task-id>\n<status>completed</status>\n"
                "<summary>Background command finished</summary>\n</task-notification>")
REMINDER = "<system-reminder>\nhook context: the date is today\n</system-reminder>"
MARKER = "LEAK-MARKER-31d7"


def _body(*user_turns, main: bool, model: str = "claude-sonnet-5-5") -> dict:
    """User turns alternate with a one-word assistant reply; each turn is a text or a list
    of text blocks. ``main`` gives the call the sub-agent launcher (main thread)."""
    msgs: list[dict] = []
    for i, turn in enumerate(user_turns):
        if i:
            msgs.append({"role": "assistant", "content": [{"type": "text", "text": "ok"}]})
        blocks = turn if isinstance(turn, list) else [turn]
        msgs.append({"role": "user", "content": [{"type": "text", "text": t} for t in blocks]})
    return {"model": model, "max_tokens": 64, "messages": msgs,
            "tools": TOOLS + ([LAUNCHER] if main else [])}


# ── kind, origin and flags of the three populations ─────────────────────────

CASES = [
    # name, body, step_kind, turn_origin, is_main_thread, is_first_call
    ("sub-agent first call (brief)",
     _body(["Investigate the parser and report.", REMINDER], main=False),
     steps.STEP_SUBAGENT_FIRST, steps.ORIGIN_SUBAGENT_BRIEF, False, True),
    ("sub-agent mid-run SendMessage",
     _body("Investigate the parser.", "Also check the lexer, then report.", main=False),
     steps.STEP_SUBAGENT_TURN, steps.ORIGIN_SUBAGENT_BRIEF, False, False),
    ("sub-agent mid-run task notification",
     _body("Investigate the parser.", NOTIFICATION, main=False),
     steps.STEP_SUBAGENT_TURN, steps.ORIGIN_TASK_NOTIFICATION, False, False),
    ("main-thread typed turn",
     _body("what is a mutex?", ["and a semaphore?", REMINDER], main=True),
     steps.STEP_TURN_FIRST, steps.ORIGIN_TYPED, True, False),
    ("main-thread task notification",
     _body("run the tests in the background", [NOTIFICATION, REMINDER], main=True),
     steps.STEP_HARNESS_TURN, steps.ORIGIN_TASK_NOTIFICATION, True, False),
    ("main-thread slash command with its expanded prompt",
     _body("hi", ["<command-message>review is running</command-message>\n<command-name>/review</command-name>"
                  "\n<command-args>12</command-args>", "Review pull request 12 for bugs."], main=True),
     steps.STEP_TURN_FIRST, steps.ORIGIN_COMMAND, True, False),
    ("main-thread command output only",
     _body("hi", "<local-command-stdout>Set model to opus</local-command-stdout>", main=True),
     steps.STEP_HARNESS_TURN, steps.ORIGIN_COMMAND, True, False),
    ("main-thread plain-text caveat line",
     _body("hi", "Caveat: The messages below were generated by the user while running local commands.",
           main=True),
     steps.STEP_HARNESS_TURN, steps.ORIGIN_COMMAND, True, False),
    ("main-thread agent message only",
     _body("hi", "<agent-message>worker finished</agent-message>", main=True),
     steps.STEP_HARNESS_TURN, steps.ORIGIN_OTHER_TAG, True, False),
    ("main-thread first call",
     _body("what is a mutex?", main=True),
     steps.STEP_TURN_FIRST, steps.ORIGIN_TYPED, True, True),
]


@pytest.mark.parametrize("name,body,kind,origin,main,first", CASES, ids=[c[0] for c in CASES])
def test_kind_origin_and_flags_tell_the_populations_apart(name, body, kind, origin, main, first):
    assert steps.step_kind(body) == kind
    assert steps.turn_origin(body) == origin
    fields = steps.turn_fields(body)
    assert (fields["is_main_thread"], fields["is_first_call"], fields["turn_origin"]) == (main, first, origin)
    assert fields["tier_text_len"] == len(steps.tier_text(body))


def test_continuations_and_side_calls_have_no_origin():
    cont = _body("read a file", main=True)
    cont["messages"] += [{"role": "assistant", "content": [{"type": "tool_use", "id": "t1", "name": "Read",
                                                            "input": {}}]},
                         {"role": "user", "content": [{"type": "tool_result", "tool_use_id": "t1",
                                                       "content": "x"}]}]
    assert steps.step_kind(cont) == steps.STEP_CONTINUATION and steps.turn_origin(cont) is None
    side = dict(_body("title this", main=True), tools=[])
    assert steps.step_kind(side) == steps.STEP_SIDE_CALL and steps.turn_origin(side) is None
    assert set(steps.TURN_ORIGINS) == {"typed", "subagent_brief", "task_notification", "command", "other_tag"}


# ── _human_text ──────────────────────────────────────────────────────────────

@pytest.mark.parametrize("tag", HARNESS_TAGS)
def test_every_shared_harness_tag_is_stripped(tag):
    name = tag if tag != "local-command" else "local-command-caveat"
    text = f"<{name}>\n{MARKER} injected\n</{name}>\nplease fix the parser"
    assert steps._human_text([{"type": "text", "text": text}]) == "please fix the parser"
    one_line = f"<{name}>{MARKER}</{name}>"
    assert steps._human_text([{"type": "text", "text": one_line}, {"type": "text", "text": "go"}]) == "go"


def test_a_literal_close_tag_inside_a_reminder_does_not_leak_the_rest():
    reminder = ("<system-reminder>\nCLAUDE.md: the strip handles <system-reminder>...</system-reminder> "
                f"blocks; also a stray `</system-reminder>` here.\n{MARKER} private rule text\n"
                "</system-reminder>")
    content = [{"type": "text", "text": reminder}, {"type": "text", "text": "what is a mutex?"}]
    assert steps._human_text(content) == "what is a mutex?"
    # the same reminder inside the typed block itself
    assert steps._human_text(f"{reminder}\nwhat is a mutex?") == "what is a mutex?"


def test_a_tag_named_inside_a_typed_sentence_is_kept():
    typed = "why does the strip only handle <system-reminder> and not <task-notification>?"
    assert steps._human_text([{"type": "text", "text": typed}]) == typed
    body = _body("hi", typed, main=True)
    assert steps.step_kind(body) == steps.STEP_TURN_FIRST and steps.turn_origin(body) == steps.ORIGIN_TYPED


def test_random_reminders_with_literal_close_tags_never_leak():
    """300 synthetic user turns: a reminder whose body quotes the close tag mid-line, then the
    typed prompt. The old non-greedy pattern leaked part of the reminder into the human text."""
    rng = random.Random(7)
    leaks_before = 0
    for i in range(300):
        quote = rng.choice(["`</system-reminder>`", "(</system-reminder>)", "x</system-reminder>y", "plain"])
        reminder = f"<system-reminder>\nline one {quote} more\n{MARKER}-{i}\n</system-reminder>"
        typed = f"question number {i}"
        content = [{"type": "text", "text": reminder}, {"type": "text", "text": typed}]
        assert steps._human_text(content) == typed
        old = re.sub(r"<system-reminder>.*?</system-reminder>", "", steps._text_of(content), flags=re.S).strip()
        leaks_before += MARKER in old
    assert leaks_before > 150   # the fixture does exercise the leak


# ── the sticky tier holds through a notification turn ───────────────────────

def test_a_notification_only_turn_is_not_classified_as_a_new_prompt():
    body = _body("refactor the parser module", [NOTIFICATION, REMINDER], main=True)
    assert steps.tier_text(body) == "refactor the parser module"
    assert steps.newest_human_text(body) == "refactor the parser module"


async def test_the_tier_policy_classifies_the_prompt_before_a_notification():
    seen: list[str] = []

    async def classify(text):
        seen.append(text)
        return {"task_type": "query", "complexity": "simple", "chain_head": [], "model": None}

    policy = pt.ClaudeTierPolicy.load()
    body = _body("what is a mutex?", "and a semaphore?", [NOTIFICATION, REMINDER], main=True)
    assert body["model"] not in policy.pinned   # a pinned model would never reach the classifier
    await policy.decide(body, "s-tf1", Stickiness(), classify=classify)
    assert seen == ["and a semaphore?"]


# ── the ledger row ───────────────────────────────────────────────────────────

async def test_every_ledger_row_carries_the_text_free_turn_fields(tmp_path, monkeypatch):
    async def choose(text, pinned, *, anthropic=False):
        return {"task_type": "query", "complexity": "simple", "chain_head": [], "model": None}
    monkeypatch.setattr(pb, "tier_classify", choose)
    app = _app(tmp_path, Upstream())
    sub = _body("Investigate the parser.", f"{MARKER} also check the lexer", main=False)
    main = _body("what is a mutex?", f"and a semaphore? {MARKER}", main=True)
    note = _body("run the tests", NOTIFICATION, main=True)
    for b in (sub, main, note):
        b["metadata"] = {"user_id": json.dumps({"session_id": "s-tf1"})}
        assert (await _post(app, b)).status_code == 200
    rows = _rows(tmp_path)
    got = [(r["step_class"], r["is_main_thread"], r["is_first_call"], r["turn_origin"], r["tier_text_len"])
           for r in rows]
    assert got == [
        ("subagent_turn", False, False, "subagent_brief", len(f"{MARKER} also check the lexer")),
        ("turn_first", True, False, "typed", len(f"and a semaphore? {MARKER}")),
        ("harness_turn", True, False, "task_notification", len("run the tests")),
    ]
    raw = (tmp_path / "proxy_calls.jsonl").read_text()
    assert MARKER not in raw and "lexer" not in raw and "semaphore" not in raw
